version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=loja
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    #restart: always
  web:
    image: vaniltonpinheiro/api-loja
    working_dir: /usr/src/app
    command: /bin/sh -c "./wait-for-it.sh db:5432 && python -u manage.py migrate && python -u manage.py collectstatic && gunicorn loja_virtual.wsgi -b :8000 --log-file -"
    ports:
      - "8000:8000"
    #restart: always
    env_file:
      - .env.prod
    depends_on:
      - db