# Generated by Django 2.2.10 on 2021-10-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Acessórios de Informática'), (2, 'Memória RAM'), (3, 'Disco Rígido/SSD'), (4, 'Placa de Vídeo'), (5, 'Gabinete'), (6, 'Placa Mãe'), (7, 'Fonte'), (8, 'Processadores'), (9, 'Eletrodomésticos'), (10, 'Cama e Mesa')], default=1),
        ),
    ]
